### ISSUE TITLE
QRCode generation BUG (Inbuilt 'BaconQrCode' package)

### ISSUE THREAD

**Issue by ohka7** [Visanduma/nova-two-factor#50]
![image](https://github.com/Visanduma/nova-two-factor/assets/64119563/20ad4556-afeb-4fee-9526-4b28d7c753d0)

![image](https://github.com/Visanduma/nova-two-factor/assets/64119563/11721e9f-7048-4f86-80df-df00c42f131e)

**Comment by lahirulhr** [comment]
Thank you for reporting the issue.

**Comment by edouardgab** [comment]
Hi there! Thanks for this package, we have been using it for a while on one of our project.

I am settings up 2FA on another project and I have that issue as well. Locally, if I set the `use_google_qr_code_api` to `true`, the QR code doesn't get generated. If I set it to `false`, it generates.

In production, it doesn't generate whether I set this `use_google_qr_code_api` to `true` or `false`. I tried multiple things but not able to make anything work. Is there any way you can guide me to find out what to looking into? I tried to work on the branch `nova4support`  as this change doesn't seems to be released yet, but no success.

Thanks for the help,

Ed

**Comment by ekazda** [comment]
This issue is closed, but I'm also having this problem in production. Locally it works without issue. If I used `use_google_qr_code_api=true`, I get the following:

<img width="1709" alt="Screenshot 2024-04-04 at 9 12 30 AM" src="https://github.com/Visanduma/nova-two-factor/assets/1107804/82c0d272-ac2c-4702-ba9c-9909b5883be4">

And if I use `use_google_qr_code_api=false`, I get this:

<img width="1542" alt="Screenshot 2024-04-04 at 9 11 06 AM" src="https://github.com/Visanduma/nova-two-factor/assets/1107804/46a93325-d599-49af-a7f0-8538f62ea596">

I'm using visanduma/nova-two-factor v2.2.11.

**Comment by gmarineau** [comment]
Same here no QR Code with both config `use_google_qr_code_api` (true or false). Work with 2.2.11 but not with 2.2.12

**Comment by lahirulhr** [comment]
Hello everyone,

Unfortunately, the Google QR API is now depreciated, and I have to move it to a new API.
now it use ``https://api.qrserver.com`` as QR API

![image](https://github.com/Visanduma/nova-two-factor/assets/13136764/30dc6d08-bab4-41e6-adb6-df4c95728481)


Also we don't use this config anymore

``'use_google_qr_code_api' => true``

instead we use
``'use_offline_qr' => false`` (default to false)

**Comment by edouardgab** [comment]
It works, thanks for your work !
